################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Add inputs and outputs from these tool invocations to the build variables 
CMD_SRCS += \
../source/HL_sys_link.cmd 

ASM_SRCS += \
../source/HL_sys_core.asm \
../source/HL_sys_intvecs.asm \
../source/HL_sys_mpu.asm \
../source/HL_sys_pmu.asm \
../source/os_portasm.asm \
../source/ramintvecs.asm 

C_SRCS += \
../source/Device_TMS570LC43.c \
../source/Fapi_UserDefinedFunctions.c \
../source/HL_adc.c \
../source/HL_can.c \
../source/HL_crc.c \
../source/HL_dcc.c \
../source/HL_ecap.c \
../source/HL_emac.c \
../source/HL_emif.c \
../source/HL_epc.c \
../source/HL_eqep.c \
../source/HL_errata.c \
../source/HL_errata_SSWF021_45.c \
../source/HL_esm.c \
../source/HL_etpwm.c \
../source/HL_gio.c \
../source/HL_het.c \
../source/HL_i2c.c \
../source/HL_mdio.c \
../source/HL_nmpu.c \
../source/HL_notification.c \
../source/HL_phy_dp83640.c \
../source/HL_phy_tlk111.c \
../source/HL_pinmux.c \
../source/HL_pom.c \
../source/HL_sci.c \
../source/HL_spi.c \
../source/HL_sys_dma.c \
../source/HL_sys_main.c \
../source/HL_sys_pcr.c \
../source/HL_sys_phantom.c \
../source/HL_sys_pmm.c \
../source/HL_sys_startup.c \
../source/HL_sys_vim.c \
../source/HL_system.c \
../source/bl_eeprom.c \
../source/bl_flash.c \
../source/i2c_io.c \
../source/main_blinky.c \
../source/mmc-hercules.c \
../source/os_croutine.c \
../source/os_event_groups.c \
../source/os_heap.c \
../source/os_list.c \
../source/os_mpu_wrappers.c \
../source/os_port.c \
../source/os_queue.c \
../source/os_tasks.c \
../source/os_timer.c \
../source/privileged_functions.c \
../source/ti_fee_Info.c \
../source/ti_fee_cancel.c \
../source/ti_fee_cfg.c \
../source/ti_fee_eraseimmediateblock.c \
../source/ti_fee_format.c \
../source/ti_fee_ini.c \
../source/ti_fee_invalidateblock.c \
../source/ti_fee_main.c \
../source/ti_fee_read.c \
../source/ti_fee_readSync.c \
../source/ti_fee_shutdown.c \
../source/ti_fee_util.c \
../source/ti_fee_writeAsync.c \
../source/ti_fee_writeSync.c 

C_DEPS += \
./source/Device_TMS570LC43.d \
./source/Fapi_UserDefinedFunctions.d \
./source/HL_adc.d \
./source/HL_can.d \
./source/HL_crc.d \
./source/HL_dcc.d \
./source/HL_ecap.d \
./source/HL_emac.d \
./source/HL_emif.d \
./source/HL_epc.d \
./source/HL_eqep.d \
./source/HL_errata.d \
./source/HL_errata_SSWF021_45.d \
./source/HL_esm.d \
./source/HL_etpwm.d \
./source/HL_gio.d \
./source/HL_het.d \
./source/HL_i2c.d \
./source/HL_mdio.d \
./source/HL_nmpu.d \
./source/HL_notification.d \
./source/HL_phy_dp83640.d \
./source/HL_phy_tlk111.d \
./source/HL_pinmux.d \
./source/HL_pom.d \
./source/HL_sci.d \
./source/HL_spi.d \
./source/HL_sys_dma.d \
./source/HL_sys_main.d \
./source/HL_sys_pcr.d \
./source/HL_sys_phantom.d \
./source/HL_sys_pmm.d \
./source/HL_sys_startup.d \
./source/HL_sys_vim.d \
./source/HL_system.d \
./source/bl_eeprom.d \
./source/bl_flash.d \
./source/i2c_io.d \
./source/main_blinky.d \
./source/mmc-hercules.d \
./source/os_croutine.d \
./source/os_event_groups.d \
./source/os_heap.d \
./source/os_list.d \
./source/os_mpu_wrappers.d \
./source/os_port.d \
./source/os_queue.d \
./source/os_tasks.d \
./source/os_timer.d \
./source/privileged_functions.d \
./source/ti_fee_Info.d \
./source/ti_fee_cancel.d \
./source/ti_fee_cfg.d \
./source/ti_fee_eraseimmediateblock.d \
./source/ti_fee_format.d \
./source/ti_fee_ini.d \
./source/ti_fee_invalidateblock.d \
./source/ti_fee_main.d \
./source/ti_fee_read.d \
./source/ti_fee_readSync.d \
./source/ti_fee_shutdown.d \
./source/ti_fee_util.d \
./source/ti_fee_writeAsync.d \
./source/ti_fee_writeSync.d 

OBJS += \
./source/Device_TMS570LC43.obj \
./source/Fapi_UserDefinedFunctions.obj \
./source/HL_adc.obj \
./source/HL_can.obj \
./source/HL_crc.obj \
./source/HL_dcc.obj \
./source/HL_ecap.obj \
./source/HL_emac.obj \
./source/HL_emif.obj \
./source/HL_epc.obj \
./source/HL_eqep.obj \
./source/HL_errata.obj \
./source/HL_errata_SSWF021_45.obj \
./source/HL_esm.obj \
./source/HL_etpwm.obj \
./source/HL_gio.obj \
./source/HL_het.obj \
./source/HL_i2c.obj \
./source/HL_mdio.obj \
./source/HL_nmpu.obj \
./source/HL_notification.obj \
./source/HL_phy_dp83640.obj \
./source/HL_phy_tlk111.obj \
./source/HL_pinmux.obj \
./source/HL_pom.obj \
./source/HL_sci.obj \
./source/HL_spi.obj \
./source/HL_sys_core.obj \
./source/HL_sys_dma.obj \
./source/HL_sys_intvecs.obj \
./source/HL_sys_main.obj \
./source/HL_sys_mpu.obj \
./source/HL_sys_pcr.obj \
./source/HL_sys_phantom.obj \
./source/HL_sys_pmm.obj \
./source/HL_sys_pmu.obj \
./source/HL_sys_startup.obj \
./source/HL_sys_vim.obj \
./source/HL_system.obj \
./source/bl_eeprom.obj \
./source/bl_flash.obj \
./source/i2c_io.obj \
./source/main_blinky.obj \
./source/mmc-hercules.obj \
./source/os_croutine.obj \
./source/os_event_groups.obj \
./source/os_heap.obj \
./source/os_list.obj \
./source/os_mpu_wrappers.obj \
./source/os_port.obj \
./source/os_portasm.obj \
./source/os_queue.obj \
./source/os_tasks.obj \
./source/os_timer.obj \
./source/privileged_functions.obj \
./source/ramintvecs.obj \
./source/ti_fee_Info.obj \
./source/ti_fee_cancel.obj \
./source/ti_fee_cfg.obj \
./source/ti_fee_eraseimmediateblock.obj \
./source/ti_fee_format.obj \
./source/ti_fee_ini.obj \
./source/ti_fee_invalidateblock.obj \
./source/ti_fee_main.obj \
./source/ti_fee_read.obj \
./source/ti_fee_readSync.obj \
./source/ti_fee_shutdown.obj \
./source/ti_fee_util.obj \
./source/ti_fee_writeAsync.obj \
./source/ti_fee_writeSync.obj 

ASM_DEPS += \
./source/HL_sys_core.d \
./source/HL_sys_intvecs.d \
./source/HL_sys_mpu.d \
./source/HL_sys_pmu.d \
./source/os_portasm.d \
./source/ramintvecs.d 

OBJS__QUOTED += \
"source\Device_TMS570LC43.obj" \
"source\Fapi_UserDefinedFunctions.obj" \
"source\HL_adc.obj" \
"source\HL_can.obj" \
"source\HL_crc.obj" \
"source\HL_dcc.obj" \
"source\HL_ecap.obj" \
"source\HL_emac.obj" \
"source\HL_emif.obj" \
"source\HL_epc.obj" \
"source\HL_eqep.obj" \
"source\HL_errata.obj" \
"source\HL_errata_SSWF021_45.obj" \
"source\HL_esm.obj" \
"source\HL_etpwm.obj" \
"source\HL_gio.obj" \
"source\HL_het.obj" \
"source\HL_i2c.obj" \
"source\HL_mdio.obj" \
"source\HL_nmpu.obj" \
"source\HL_notification.obj" \
"source\HL_phy_dp83640.obj" \
"source\HL_phy_tlk111.obj" \
"source\HL_pinmux.obj" \
"source\HL_pom.obj" \
"source\HL_sci.obj" \
"source\HL_spi.obj" \
"source\HL_sys_core.obj" \
"source\HL_sys_dma.obj" \
"source\HL_sys_intvecs.obj" \
"source\HL_sys_main.obj" \
"source\HL_sys_mpu.obj" \
"source\HL_sys_pcr.obj" \
"source\HL_sys_phantom.obj" \
"source\HL_sys_pmm.obj" \
"source\HL_sys_pmu.obj" \
"source\HL_sys_startup.obj" \
"source\HL_sys_vim.obj" \
"source\HL_system.obj" \
"source\bl_eeprom.obj" \
"source\bl_flash.obj" \
"source\i2c_io.obj" \
"source\main_blinky.obj" \
"source\mmc-hercules.obj" \
"source\os_croutine.obj" \
"source\os_event_groups.obj" \
"source\os_heap.obj" \
"source\os_list.obj" \
"source\os_mpu_wrappers.obj" \
"source\os_port.obj" \
"source\os_portasm.obj" \
"source\os_queue.obj" \
"source\os_tasks.obj" \
"source\os_timer.obj" \
"source\privileged_functions.obj" \
"source\ramintvecs.obj" \
"source\ti_fee_Info.obj" \
"source\ti_fee_cancel.obj" \
"source\ti_fee_cfg.obj" \
"source\ti_fee_eraseimmediateblock.obj" \
"source\ti_fee_format.obj" \
"source\ti_fee_ini.obj" \
"source\ti_fee_invalidateblock.obj" \
"source\ti_fee_main.obj" \
"source\ti_fee_read.obj" \
"source\ti_fee_readSync.obj" \
"source\ti_fee_shutdown.obj" \
"source\ti_fee_util.obj" \
"source\ti_fee_writeAsync.obj" \
"source\ti_fee_writeSync.obj" 

C_DEPS__QUOTED += \
"source\Device_TMS570LC43.d" \
"source\Fapi_UserDefinedFunctions.d" \
"source\HL_adc.d" \
"source\HL_can.d" \
"source\HL_crc.d" \
"source\HL_dcc.d" \
"source\HL_ecap.d" \
"source\HL_emac.d" \
"source\HL_emif.d" \
"source\HL_epc.d" \
"source\HL_eqep.d" \
"source\HL_errata.d" \
"source\HL_errata_SSWF021_45.d" \
"source\HL_esm.d" \
"source\HL_etpwm.d" \
"source\HL_gio.d" \
"source\HL_het.d" \
"source\HL_i2c.d" \
"source\HL_mdio.d" \
"source\HL_nmpu.d" \
"source\HL_notification.d" \
"source\HL_phy_dp83640.d" \
"source\HL_phy_tlk111.d" \
"source\HL_pinmux.d" \
"source\HL_pom.d" \
"source\HL_sci.d" \
"source\HL_spi.d" \
"source\HL_sys_dma.d" \
"source\HL_sys_main.d" \
"source\HL_sys_pcr.d" \
"source\HL_sys_phantom.d" \
"source\HL_sys_pmm.d" \
"source\HL_sys_startup.d" \
"source\HL_sys_vim.d" \
"source\HL_system.d" \
"source\bl_eeprom.d" \
"source\bl_flash.d" \
"source\i2c_io.d" \
"source\main_blinky.d" \
"source\mmc-hercules.d" \
"source\os_croutine.d" \
"source\os_event_groups.d" \
"source\os_heap.d" \
"source\os_list.d" \
"source\os_mpu_wrappers.d" \
"source\os_port.d" \
"source\os_queue.d" \
"source\os_tasks.d" \
"source\os_timer.d" \
"source\privileged_functions.d" \
"source\ti_fee_Info.d" \
"source\ti_fee_cancel.d" \
"source\ti_fee_cfg.d" \
"source\ti_fee_eraseimmediateblock.d" \
"source\ti_fee_format.d" \
"source\ti_fee_ini.d" \
"source\ti_fee_invalidateblock.d" \
"source\ti_fee_main.d" \
"source\ti_fee_read.d" \
"source\ti_fee_readSync.d" \
"source\ti_fee_shutdown.d" \
"source\ti_fee_util.d" \
"source\ti_fee_writeAsync.d" \
"source\ti_fee_writeSync.d" 

ASM_DEPS__QUOTED += \
"source\HL_sys_core.d" \
"source\HL_sys_intvecs.d" \
"source\HL_sys_mpu.d" \
"source\HL_sys_pmu.d" \
"source\os_portasm.d" \
"source\ramintvecs.d" 

C_SRCS__QUOTED += \
"../source/Device_TMS570LC43.c" \
"../source/Fapi_UserDefinedFunctions.c" \
"../source/HL_adc.c" \
"../source/HL_can.c" \
"../source/HL_crc.c" \
"../source/HL_dcc.c" \
"../source/HL_ecap.c" \
"../source/HL_emac.c" \
"../source/HL_emif.c" \
"../source/HL_epc.c" \
"../source/HL_eqep.c" \
"../source/HL_errata.c" \
"../source/HL_errata_SSWF021_45.c" \
"../source/HL_esm.c" \
"../source/HL_etpwm.c" \
"../source/HL_gio.c" \
"../source/HL_het.c" \
"../source/HL_i2c.c" \
"../source/HL_mdio.c" \
"../source/HL_nmpu.c" \
"../source/HL_notification.c" \
"../source/HL_phy_dp83640.c" \
"../source/HL_phy_tlk111.c" \
"../source/HL_pinmux.c" \
"../source/HL_pom.c" \
"../source/HL_sci.c" \
"../source/HL_spi.c" \
"../source/HL_sys_dma.c" \
"../source/HL_sys_main.c" \
"../source/HL_sys_pcr.c" \
"../source/HL_sys_phantom.c" \
"../source/HL_sys_pmm.c" \
"../source/HL_sys_startup.c" \
"../source/HL_sys_vim.c" \
"../source/HL_system.c" \
"../source/bl_eeprom.c" \
"../source/bl_flash.c" \
"../source/i2c_io.c" \
"../source/main_blinky.c" \
"../source/mmc-hercules.c" \
"../source/os_croutine.c" \
"../source/os_event_groups.c" \
"../source/os_heap.c" \
"../source/os_list.c" \
"../source/os_mpu_wrappers.c" \
"../source/os_port.c" \
"../source/os_queue.c" \
"../source/os_tasks.c" \
"../source/os_timer.c" \
"../source/privileged_functions.c" \
"../source/ti_fee_Info.c" \
"../source/ti_fee_cancel.c" \
"../source/ti_fee_cfg.c" \
"../source/ti_fee_eraseimmediateblock.c" \
"../source/ti_fee_format.c" \
"../source/ti_fee_ini.c" \
"../source/ti_fee_invalidateblock.c" \
"../source/ti_fee_main.c" \
"../source/ti_fee_read.c" \
"../source/ti_fee_readSync.c" \
"../source/ti_fee_shutdown.c" \
"../source/ti_fee_util.c" \
"../source/ti_fee_writeAsync.c" \
"../source/ti_fee_writeSync.c" 

ASM_SRCS__QUOTED += \
"../source/HL_sys_core.asm" \
"../source/HL_sys_intvecs.asm" \
"../source/HL_sys_mpu.asm" \
"../source/HL_sys_pmu.asm" \
"../source/os_portasm.asm" \
"../source/ramintvecs.asm" 


