#!/bin/bash

echo "Running pre-commit hook: Clang-format"

# Check if clang-format is installed
if ! which clang-format > /dev/null; then
    echo "clang-format not installed, installing now..."
    sudo apt-get install --no-install-recommends -y clang-format
fi

STYLE=$(git config --get hooks.clangformat.style)
if [ -n "${STYLE}" ] ; then
  STYLEARG="-style=${STYLE}"
else
  STYLEARG=""
fi

case "${1}" in
  --about )
    echo "Runs clang-format on source files"
    ;;
  * )
    for file in $(git diff --cached --name-only); do
      if [[ $(dirname "$file") != "source" && 
        $(dirname "$file") != "include" && 
        $(dirname "$file") != "FreeRTOS-Plus-CLI" &&
        $(dirname "$file") != reliance_edge/* &&
        $(dirname "$file") != "F021_API" ]]; then

        if [[ $file == *.c || $file == *.h || $file == *.cpp || $file == *.hpp ]]; then
          echo "Formatting: $file"
          clang-format -i ${STYLEARG} ${file}
          git add ${file}
        fi
        
      fi
    done
    ;;
esac