name: clang-format Check
on: [pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - check: '.'
            exclude: '(F021_API|source|include|reliance_edge|ex2_hal/ex2_uhf_software|ex2_sdr|FreeRTOS-Plus-CLI|libcsp|test)' # Exclude file paths containing "hello" or "world"
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.9.0
      with:
        clang-format-version: '14'
        check-path: ${{ matrix.path['check'] }}
        exclude-regex: ${{ matrix.path['exclude'] }}
