name: tag-on-pr-close
on:
  push:
    branches:
      - master
jobs:
  tag-default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: tag the default repository
        run: ./.github/scripts/tag.sh "$GITHUB_ACTOR" "$GITHUB_SHA"
        shell: bash
