name: tag-on-pr-close
on:
  push:
    branches:
      - master
jobs:
  tag-default:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: tag the default repository
      run: echo "actor $env:GITHUB_ACTOR"
      run: echo "branch ${GITHUB_REF#refs/heads/}
      run: ./.github/scripts/tag.sh ${GITHUB_REF#refs/heads/}
      shell: bash
