name: unit-tests

on:
  workflow_dispatch: # Manually run action for now

jobs:
  sync:
    name: 'Run unit tests on ex2_obc_software'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    
    steps:
      # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.SUBMODULE_CONTENT_PULL_KEY }} # Needed to checkout private submodules
        submodules: 'recursive'

    - name: Create version.sh
      run: |
        ./version.sh
    
    - name: Update submodules to master/main branch
      run: |
        git submodule init
        git submodule update
        git submodule foreach 'git checkout master || :'
        git submodule foreach git pull
    
    - name: Run unit tests 
      uses: AlbertaSat/CCS_v10_4_build_action@v0.2.1 #cgreen integration
